api_version = "2025-10"
uid = "31325b60-fd02-a042-ae7c-e2733d4dcfded3e83bdc"

[[extensions]]
name = "tv-licence-verification"
handle = "tv-licence-verification"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"

[extensions.capabilities]
api_access = true
network_access = true
